### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by Atif0604** [srinidh-007/HackotberFest2021#87]
Hey @srinidh-007 i want to add shell sort in cpp

**Comment by ganesh1729ganesh** [comment]
I know exactly how shell sort works and and I know how to code it in cpp. Can you please assign it to me?

**Comment by Atif0604** [comment]
Hey @ganesh1729ganesh this issue is created by me not by project admins

**Comment by srinidh-007** [comment]
why are you creating issues that are not at all issues
